name = "muxa-docs"
main = ".worker-next/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = ".worker-next/public"

# Build command removed - build separately with: bunx @opennextjs/cloudflare build

[[routes]]
pattern = "docs.den.ai/muxa/*"
zone_name = "den.ai"

[env.production]
vars = { NODE_ENV = "production", NEXT_PUBLIC_BASE_URL = "https://docs.den.ai" }