name: CI

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Verify Bun installation
        run: |
          echo "Bun version:"
          bun --version
          echo "Bun location:"
          which bun
          echo "PATH:"
          echo $PATH

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run TypeScript checks
        run: bun run typecheck

      - name: Run linting
        run: bun run lint

      - name: Check formatting
        run: bun run format

      - name: Run tests
        run: bun test:clean
        working-directory: packages/muxa

      # Build verification - ensures the project can be built successfully
      # The actual build artifacts for publishing are created in the release workflow
      - name: Build project (verification only)
        run: bun run build

      - name: Build muxa package (verification only)
        run: bun run build
        working-directory: packages/muxa
