name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create GitHub releases

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      # IMPORTANT: Copy README from root to package before publishing
      # This ensures npm shows the full documentation
      - name: Copy README for npm
        run: cp README.md packages/muxa/README.md

      - name: Publish to npm
        run: npm publish --access public
        working-directory: packages/muxa
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get tag name
        id: tag
        run: |
          TAG_NAME="${{ github.ref }}"
          TAG_NAME="${TAG_NAME#refs/tags/}"
          echo "name=$TAG_NAME" >> $GITHUB_OUTPUT
          VERSION="${TAG_NAME#v}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Extract changelog for release
        id: changelog
        run: |
          VERSION="${{ steps.tag.outputs.version }}"

          # Extract the changelog section for this version
          awk -v version="$VERSION" '
            /^## \[/ {
              if (found) exit
              if ($0 ~ "\\[" version "\\]") {
                found = 1
                next
              }
            }
            found && /^## \[/ { exit }
            found { print }
          ' packages/muxa/CHANGELOG.md > release_notes.md

          # Set as output for GitHub release
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          cat release_notes.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.name }}
          name: Release ${{ steps.tag.outputs.name }}
          body: ${{ steps.changelog.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false
