# TODO: Enable this workflow when ready for automated releases
# Currently disabled - remove .disabled extension to activate
name: Release

# DISABLED - Uncomment when ready
# on:
#   push:
#     tags:
#       - 'v*'

on:
  workflow_dispatch: # Manual trigger only for now

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test
        working-directory: packages/muxa

      - name: Build
        run: bun run build

      # IMPORTANT: Copy README from root to package before publishing
      # This ensures npm shows the full documentation
      - name: Copy README for npm
        run: cp README.md packages/muxa/README.md

      - name: Publish to npm
        run: npm publish --access public
        working-directory: packages/muxa
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
